feat(KSM-4791, nav.js, blog.js, home.js, count.js):
KQED/frontend-training-jguardado pull request #10
Opened 2023-08-10 20:54 UTC by Jmg047

Progress check: I plan to place the 'show' button in the body outside of the navbar component, though for now I'm having some trouble with the height of my buttons, ideally they ought to be max-hight of the navbar (note: this is subjective and doesn't have to be a mandatory implementation though). Any Feedback is appreciated!

2023-08-14 15:38 UTC, pamelagilmour reviewed
Looks good so far! 
+ As a visual learner, one trick I learned from Jason is to add a border to every element, or at least the elements you are style debugging and their container(s) etc. It helps to visualized where the issue lies. Also have you tried using the DevTools? It can also be another way to debug styles.

+ I noticed your style sheet has some inconsistent spacing which can sometimes lend to styling bugs. I don't think its causing an issue currently but it's good to double check.

+ I noticed you are using flex in your nav bar. I think that's where the styling mismatch you are having lies. I think it might be with lines 90 and 91 in App.scss and/or putting each section of your nav bar in a " inner container" or <div>. There are many ways to move forward. Also setting a width for your buttons....LMK if you want to pair and I can show you all that stuff 👆 in action.

2023-08-15 18:27 UTC, Jmg047 commented
React Routes have been implemented for different pages with different content. There is a navbar with buttons that go to different routes and a form. Each route has different content while the navbar stays constant at the top of each page.

``Testing:``
Navigate to ``home``, ``counter``, ``about``, & ``contact``
mess around with screen size for the mobile responsiveness

2023-08-15 22:17 UTC, pamelagilmour requested changes
Okay looks good so far! Double check your stylesheet.

2023-08-15 22:17 UTC, pamelagilmour commented on client/src/App.scss
> +  .navbar {
It looks like maybe you are repeating styles, maybe?

2023-08-15 22:17 UTC, pamelagilmour commented on client/src/component/nav.js
Congrats on this.

2023-08-15 22:19 UTC, pamelagilmour commented
I just left a review, but I forgot to check mobile. The mobile needs a little bit of work, much of the page is off screen. I'm not sure if that is what you are intending or not.

2023-08-15 22:22 UTC, Jmg047 commented
Good catch! I definitely didn't intend for everything to be off screen on mobile, I'll go ahead and fix that and make another PR

2023-08-18 18:57 UTC, pamelagilmour approved these changes
LGTM!!! Great job!

2023-08-24 16:25 UTC, merged